trigger:
- dev/jminor/azdobuild

resources:
  containers:
  - container: rtos-build
    image: rnd-builds.repos.natinst.com/rtos/nilrt-build:0.3
    options:

jobs:
- job: Build_OpenEmbedded
  container: rtos-build
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  steps:
  - script: |
      echo "This repo is: $(Build.Repository.Name)"
      export REPO_NAME=`echo $(Build.Repository.Name) | sed -E "s/.*\///"`
      echo "Using this as repo name $REPO_NAME"
      # Since we are going to clone the parent repo and mangle it, do this
      # in a temporary location only
      cd $(Agent.TempDirectory)
      echo "We are at:"
      pwd
      echo "here is what's here"
      ls -al
      git clone https://github.com/ni/nilrt
      cd nilrt
      git checkout nilrt/master/dunfell
      git submodule init
      git submodule update --remote --checkout
      rm -r sources/$REPO_NAME
      cp -r $(Build.SourcesDirectory) $(Agent.TempDirectory)/nilrt/sources/$REPO_NAME
      cd $(Agent.TempDirectory)/nilrt/sources
      ls -al
      cd $REPO_NAME
      ls -al
    name: Copy_repos

  - script: |
      cd $(Agent.TempDirectory)/nilrt
      export MACHINE=x64
      echo "We are at:"
      pwd
      echo "here is what's here"
      ls -al
      source ni-oe-init-build-env
      bitbake packagegroup-ni-coreimagerepo
      bitbake --continue packagegroup-ni-extra
      bitbake package-index
      bitbake restore-mode-image
    name: Build
